/* 年まとめ・教育費マスタの計算を、編集可能な入力データから再現する計算層。 */
window.PlanEngine=(()=>{
 const n=x=>Number.isFinite(Number(x))?Number(x):0;const fiscalStart=p=>Math.max(1,Math.min(12,n(p.fiscalStartMonth)||1));const calendarYear=(label,month,start)=>label+(month<start?1:0);
 const sorted=a=>[...(a||[])].sort((x,y)=>n(x.startYear)-n(y.startYear));
 const stage=(list,year,fallback)=>{let v=fallback;for(const x of sorted(list))if(n(x.startYear)<=year)v=x;return v};
 const rateTable=[{min:0,rate:1},{min:1e6,rate:.85},{min:1.5e6,rate:.82},{min:2e6,rate:.8},{min:3e6,rate:.79},{min:4e6,rate:.78},{min:5e6,rate:.77},{min:6e6,rate:.75},{min:7e6,rate:.74},{min:8e6,rate:.73},{min:9e6,rate:.72},{min:1e7,rate:.7},{min:1.2e7,rate:.68},{min:1.5e7,rate:.65}];
 function takeHome(gross,table=rateTable){let r=1;for(const row of [...table].sort((a,b)=>n(a.min)-n(b.min)))if(gross>=n(row.min))r=n(row.rate);return gross*r}
 function promotionSummary(p,target=0){let points=0,annualGross=0,annualNet=0;return (p.promotion||[]).map((r,i)=>{const half=n(r.monthlyPay)*n(r.coefficient)+n(r.performanceBonus)/2,gross=n(r.monthlyPay)*12+half*(i===0?4/3:2),net=gross*n(r.netRate||.72);annualGross+=gross;annualNet+=net;points+=n(r.retirementPoints);const retirement=n(r.retirementRatio)*points*10,prepay=n(p.prepayMonthly||17500)*12*(i+1),retirementTotal=retirement+prepay,years=i+1,deduction=years<=20?400000*years:(800+70*(years-20))*10000,taxable=Math.floor((Math.max(0,(retirementTotal-deduction)/2)+1e-6)/1000)*1000;let tax=0;for(const [limit,rate,sub] of [[1950000,.05,0],[3300000,.1,97500],[6950000,.2,427500],[9000000,.23,636000],[18000000,.33,1536000],[40000000,.4,2796000],[Infinity,.45,4796000]])if(taxable<=limit){tax=(taxable*rate-sub)*1.021;break}const retirementNet=retirementTotal-tax-taxable*.1,overtime10=n(r.monthlyPay)*3*1.25/460*10,neededHours=overtime10?Math.max(0,10*(n(target)-gross)/overtime10):0;return {year:n(r.year),role:r.role,rating:r.rating,gross,net,annualGross,annualNet,retirement,prepay,retirementTotal,retirementNet,neededHours,monthlyNeededHours:neededHours/12}})}
 function parentIncome(p,year,plan){if(!p)return {amount:0,mode:'未設定'};const s=stage(p.stages,year,{mode:'正社員'});const mode=s.mode||'正社員';if(mode==='専業主婦'||mode==='無収入')return {amount:0,mode};if(p.usePromotion&&mode==='正社員'){const r=(p.promotion||[]).find(x=>n(x.year)===year);if(r){const half=n(r.monthlyPay)*n(r.coefficient)+n(r.performanceBonus)/2;const gross=n(r.monthlyPay)*12+half*(year===n(plan.startYear)?4/3:2);return {amount:gross*n(r.netRate||.72),mode}}}const v=(p.patterns||{})[mode]||{};const override=(p.yearly||{})[String(year)]?.[mode];if(override!==undefined&&override!==null&&override!=='')return {amount:n(override),mode};const start=n(v.startYear)||n(plan.startYear);let anchor=start,base=n(v.base);for(const mark of sorted(v.milestones||[]))if(n(mark.startYear)<=year){anchor=n(mark.startYear);base=n(mark.amount)}const elapsed=Math.max(0,year-anchor);if(v.raiseType==='定額')base+=n(v.raiseAmount)*elapsed;else if(v.raiseType==='定率')base*=Math.pow(1+n(v.raisePercent)/100,elapsed);let amount=v.amountType==='額面'?takeHome(base,plan.taxBrackets):base;return {amount,mode}}
 function childCost(child,year,master,masterOverrides={}){const age=year-n(child.birthYear);if(age<0||age>24)return {age,amount:0,base:0,school:0,tuition:0,scholarship:0,parts:[]};const row=master.ages[String(age)]||{},choices=child.choices||{},parts=[],over=masterOverrides[String(age)]||{};let base=n(over['基本生活費']??row['基本生活費']);for(const label of Object.values(choices)){if(label&&label!=='なし'&&label!=='院/なし'){let cost=n(over[label]??row[label]);if(child.overrides&&child.overrides[label]!==undefined&&child.overrides[label]!=='')cost=n(child.overrides[label]);if(cost){parts.push({name:label,amount:cost});}}}let school=parts.reduce((a,b)=>a+b.amount,0);let tuition=base+school+n(child.extraAnnual);const sch=child.scholarship||{},eligible=age>=n(sch.startAge)&&age<n(sch.startAge)+n(sch.years);const scholarship=eligible?n(sch.annual):0;return {age,amount:Math.max(0,tuition-scholarship),base,school,tuition,scholarship,parts}}
 function annual(plan,master){const res=[],start=n(plan.startYear),h=Math.max(1,Math.min(80,n(plan.horizon)||40));let cash=n(plan.initialCash),invest=n(plan.initialInvest),applianceBalance=Math.max(0,Math.min(cash,n(plan.applianceFund?.initialBalance)));for(let i=0;i<h;i++){const year=start+i,fs=fiscalStart(plan),sequence=Array.from({length:12},(_,k)=>(fs-1+k)%12+1),periodMonths=i===0&&fs!==1?12-sequence.indexOf(Math.max(1,Math.min(12,n(plan.firstYearStartMonth)||fs))):12,periodFactor=periodMonths/12;const raw1=parentIncome(plan.parents?.[0],year,plan),raw2=parentIncome(plan.parents?.[1],year,plan),p1={...raw1,amount:raw1.amount*periodFactor},p2={...raw2,amount:raw2.amount*periodFactor},baseIncome=p1.amount+p2.amount;let eventIncome=0,eventExpense=0,events=[];for(const e of plan.events||[]){if(!e.enabled)continue;const from=n(e.startYear),to=n(e.endYear)||from,period=n(e.interval)||0,oneOff=!period||!n(e.endYear);if(oneOff?year===from:year>=from&&year<=to&&(year-from)%period===0){if(i===0&&fs!==1&&n(e.month)>=1&&n(e.month)<=12&&sequence.indexOf(n(e.month))<12-periodMonths)continue;eventIncome+=n(e.income);eventExpense+=n(e.expense);events.push(e)}}if(plan.retirement&&n(plan.retirement.age)>0&&year-start+n(plan.baseAge)===n(plan.retirement.age)){let payout=n(plan.retirement.payout);if(plan.retirement.usePromotionPayout){const s=promotionSummary(plan.parents?.[0]||{}).find(x=>x.year===year);if(s)payout=s.retirement}eventIncome+=payout}
 const exp=stage(plan.expenseStages,year,{profileId:'A'}),profile=(plan.expenseProfiles||{})[exp.profileId]||[];let living=0;for(const item of profile)living+=(n(item.monthly)*12+n(item.annual))*(item.inflation?Math.pow(1+n(plan.inflation)/100,i):1)*periodFactor;
 const home=stage(plan.housingStages,year,{profileId:'A'}),housingProfile=(plan.housingProfiles||{})[home.profileId]||{};const months=year===start?(fs!==1?(n(plan.firstYearHousingMonths)&&n(plan.firstYearHousingMonths)!==12?n(plan.firstYearHousingMonths):periodMonths):n(plan.firstYearHousingMonths)||12):12;const housing=n(housingProfile.monthly)*months+n(housingProfile.annual);
 const children=(plan.children||[]).map(c=>{const cost=childCost(c,year,master,plan.masterOverrides);return {name:c.name,...cost,amount:cost.amount*periodFactor,base:cost.base*periodFactor,school:cost.school*periodFactor,tuition:cost.tuition*periodFactor,scholarship:cost.scholarship*periodFactor,parts:cost.parts.map(part=>({...part,amount:part.amount*periodFactor}))}});const education=children.reduce((a,c)=>a+c.amount,0);
 const appliance=plan.applianceFund||{},cycle=Math.max(1,Math.floor(n(appliance.cycleYears)||10)),firstPurchase=n(appliance.firstPurchaseYear)||start+cycle,purchaseMonth=Math.max(1,Math.min(12,n(appliance.purchaseMonth)||fs)),purchaseDue=!!appliance.enabled&&n(appliance.purchaseCost)>0&&year>=firstPurchase&&(year-firstPurchase)%cycle===0,monthIncluded=!(i===0&&fs!==1&&sequence.indexOf(purchaseMonth)<12-periodMonths),applianceExpense=purchaseDue&&monthIncluded?n(appliance.purchaseCost):0,applianceSetAside=appliance.enabled?n(appliance.purchaseCost)/cycle/12*periodMonths:0,plannedApplianceBalance=appliance.enabled?Math.max(0,applianceBalance+applianceSetAside-applianceExpense):0;
 const totalIncome=baseIncome+eventIncome,totalExpense=living+housing+eventExpense+education+applianceExpense,net=totalIncome-totalExpense;
 const trigger=plan.drawdownType==='0円'?0:plan.drawdownType==='手入力金額'?n(plan.drawdownAmount):n(plan.reserve);
 const previousCash=cash,previousInvest=invest,preCash=cash+net,withdraw=Math.min(Math.max(0,trigger-preCash),Math.max(0,invest));
 const annualBase=n(plan.annualContribution)*periodFactor,maxInvest=n(plan.investAnnualCap)||Infinity,possible=Math.max(0,preCash-n(plan.reserve)-plannedApplianceBalance),normal=Math.min(annualBase,possible),extra=Math.max(0,preCash-normal-n(plan.investTrigger)-plannedApplianceBalance),contribution=Math.min(normal+extra,maxInvest);
 cash=preCash-contribution+withdraw;applianceBalance=Math.min(Math.max(0,cash),plannedApplianceBalance);const gain=(previousInvest+(contribution-withdraw)/2)*n(plan.returnRate)/100*periodFactor;invest=previousInvest+contribution-withdraw+gain;
 res.push({year,age:n(plan.baseAge)+i,parent1:p1,parent2:p2,baseIncome,eventIncome,totalIncome,living,housing,eventExpense,education,applianceExpense,applianceSetAside,applianceBalance,freeCash:cash-applianceBalance,totalExpense,net,contribution,withdraw,gain,cash,invest,assets:cash+invest,events,children,previousCash,previousInvest,expenseProfile:exp.profileId,housingProfile:home.profileId});}
 return res}
 function monthlyShortfall(plan,years){let cash=n(plan.initialCash),invest=n(plan.initialInvest),first=null,byMonth=[];for(const y of years){const fs=fiscalStart(plan),sequence=Array.from({length:12},(_,i)=>(fs-1+i)%12+1),from=y.year===n(plan.startYear)?Math.max(0,sequence.indexOf(Math.max(1,Math.min(12,n(plan.firstYearStartMonth)||fs)))):0;const divisor=y.year===n(plan.startYear)&&fs!==1?sequence.length-from:12;for(const m of sequence.slice(from)){const key=`${calendarYear(y.year,m,fs)}-${String(m).padStart(2,'0')}`;let income=y.baseIncome/divisor+(y.eventIncome-y.events.reduce((s,e)=>s+n(e.income),0))/divisor,expense=(y.living+y.housing+y.education)/divisor;for(const e of y.events){if(n(e.month)>=1&&n(e.month)<=12){if(n(e.month)===m){income+=n(e.income);expense+=n(e.expense)}}else{income+=n(e.income)/divisor;expense+=n(e.expense)/divisor}}if(y.applianceExpense&&m===Math.max(1,Math.min(12,n(plan.applianceFund?.purchaseMonth)||fs)))expense+=y.applianceExpense;
 cash+=income-expense-y.contribution/divisor;
 if(cash<n(plan.reserve)&&invest>0){const w=Math.min(invest,Math.max(0,n(plan.reserve)-cash));cash+=w;invest-=w}
 invest+=y.contribution/divisor;invest*=Math.pow(Math.max(0,1+n(plan.returnRate)/100),1/12);
 if(cash<0&&!first)first=key;byMonth.push({key,cash,invest});}}
 return {first,months:byMonth}}
 return {annual,monthlyShortfall,parentIncome,childCost,takeHome,promotionSummary,rateTable};
})();
