window.PlanModel=(()=>{
 const current=new Date().getFullYear();
 const expenseNames=['食費','交際費','日用品','水道光熱','通信費','サブスク','被服・美容','医療','交通費','趣味','お小遣い（本人）','お小遣い（パートナー）','保険','記念日','家族レジャー'];
 const profile=()=>expenseNames.map(name=>({name,monthly:0,annual:0,inflation:false}));
 const parent=(name)=>({name,birthYear:2001,stages:[{startYear:2026,mode:'正社員'}],patterns:{'正社員':{base:0,amountType:'手取り',raiseType:'定率',raisePercent:1,raiseAmount:0,startYear:2026}},yearly:{},usePromotion:false,promotion:[],targetAnnual:10000000,prepayMonthly:17500,incomeNote:''});
 const child=(birthYear=current+2)=>({name:'子ども',birthYear,choices:{preschool:'保育園・幼稚園',primary:'小学校/公立',middle:'中学校/公立',high:'高校/公立',university:'大学/国公立文系',graduate:'院/なし',middleJuku:'塾/中学校/なし',highJuku:'塾/高校/なし'},scholarship:{startAge:18,annual:0,years:0},extraAnnual:0,overrides:{}});
 const empty=()=>({version:2,name:'新しいプラン',startYear:2026,fiscalStartMonth:4,horizon:40,baseAge:25,firstYearStartMonth:4,firstYearHousingMonths:12,initialCash:0,initialInvest:0,reserve:300000,annualContribution:0,investAnnualCap:7200000,investTrigger:2000000,returnRate:5,inflation:0,drawdownType:'生活防衛資金',drawdownAmount:0,parents:[parent('本人'),parent('パートナー')],expenseProfileNames:{A:'標準生活',B:'別の生活'},expenseProfiles:{A:profile(),B:profile()},expenseStages:[{startYear:2026,profileId:'A'}],housingProfiles:{A:{name:'現在の住まい',monthly:0,annual:0},B:{name:'次の住まい',monthly:0,annual:0}},housingStages:[{startYear:2026,profileId:'A'}],children:[],masterOverrides:{},events:[],retirement:{age:65,payout:0,usePromotionPayout:false},actuals:[],personalActuals:[],comparisonContext:{household:'couple',area:'metro'},referenceBudgets:{},applianceFund:{enabled:false,initialBalance:0,purchaseCost:0,cycleYears:10,firstPurchaseYear:2036,purchaseMonth:4}});
 const demo=()=>{const p=empty();p.name='見本：共働き・子ども2人';p.initialCash=2000000;p.initialInvest=500000;p.annualContribution=600000;p.parents[0].patterns['正社員'].base=5000000;p.parents[0].patterns['正社員'].raisePercent=2;p.parents[1].patterns['正社員'].base=3500000;p.parents[1].patterns['正社員'].raisePercent=1;p.parents[1].patterns['育休']={base:1000000,amountType:'手取り',raiseType:'なし',raisePercent:0,raiseAmount:0,startYear:current+3};p.parents[1].patterns['パート']={base:1600000,amountType:'手取り',raiseType:'なし',raisePercent:0,raiseAmount:0,startYear:current+4};p.parents[1].stages=[{startYear:current,mode:'正社員'},{startYear:current+3,mode:'育休'},{startYear:current+4,mode:'パート'},{startYear:current+8,mode:'正社員'}];p.expenseProfiles.A.forEach(x=>{const values={'食費':65000,'交際費':20000,'日用品':12000,'水道光熱':22000,'通信費':10000,'サブスク':3000,'被服・美容':12000,'医療':5000,'交通費':10000,'趣味':10000,'お小遣い（本人）':20000,'お小遣い（パートナー）':20000,'保険':10000,'記念日':5000,'家族レジャー':10000};x.monthly=values[x.name]||0});p.housingProfiles.A.monthly=100000;p.children=[child(current+2),child(current+5)];p.children[0].name='子ども1';p.children[1].name='子ども2';p.events=[{name:'引っ越し',startYear:current+7,endYear:0,interval:0,month:4,income:0,expense:600000,enabled:true}];return p};
 const clone=x=>JSON.parse(JSON.stringify(x));
 return {empty,demo,child,parent,clone,expenseNames};
})();
