// このテストは，家計簿の画面間の金額一致と，予定・実績・資産移動の計算を確認します．
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../household/app.js'),'utf8');
const names=['migrate','ensureMonth','totals','blankSummary','categoryBucket','categoryPlanAt','applyCategoryPlan','endCategoryFrom','removePlanRule','summaryFromMonth','basePlan','ensurePlanMonth','planFor','actualBucketEntered','monthFlow','timeline','plannedAt','displayedPlanned','displayedActual','budgetStats','budgetDifference','renderMonthBudget','outlookCard'];
function environment(){
 const nodes={};const ctx={console,crypto:{randomUUID:()=>String(Math.random())},localStorage:{setItem(){}},activeMonth:'2026-10',n:x=>Number(String(x??'').replaceAll(',',''))||0,fmt:x=>new Intl.NumberFormat('ja-JP').format(Math.round(x)),yen:x=>new Intl.NumberFormat('ja-JP').format(Math.round(x))+'円',signed:x=>(x>0?'+':'')+new Intl.NumberFormat('ja-JP').format(Math.round(x))+'円',esc:String,signClass:x=>x>=0?'positive':'negative',varianceClass:()=>'',statusText:x=>x,uuid:()=>String(Math.random()),monthNow:()=>'2026-10',fiscal:()=>2026,save(){},fresh:()=>({format:'jp.household.book',categories:[],months:[],planMonths:[]}),sortCategories:cats=>cats,categoryAvailable:(c,month='')=>c?.active!==false&&(!month||(!c.activeFrom||c.activeFrom<=month)&&(!c.inactiveFrom||month<c.inactiveFrom)),isSpecialCategory:c=>/特別収入|特別支出/.test(c?.group||'')||/特別収入|特別支出/.test(c?.name||''),summaryKeys:['salary','specialIncome','living','fixed','nisa','regular','specialExpense','otherSaving','purposeSaving'],$:id=>nodes[id]??=( {dataset:{},open:false,innerHTML:'',textContent:'',querySelector:()=>null}),data:null};
 ctx.catMap=()=>Object.fromEntries(ctx.data.categories.map(c=>[c.id,c]));ctx.value=(r,id)=>r.values[id]||{planned:0,actual:0,comment:''};ctx.visibleCats=r=>ctx.data.categories.filter(c=>ctx.categoryAvailable(c,r.month)&&(c.scope!=='month'||c.month===r.month));vm.createContext(ctx);
 for(const name of names){const start=source.indexOf('function '+name+'(');assert(start>=0,name);const end=source.indexOf('\nfunction ',start);let code=source.slice(start,end<0?source.length:end);if(name==='migrate'||name==='ensureMonth'||name==='timeline'||name==='outlookCard')code=code.split('\n')[0];vm.runInContext(code,ctx)}
 ctx.data={format:'jp.household.book',schemaVersion:12,name:'test',categories:[],months:[],planMonths:[],planRules:[],plannedSpecials:[],recurringPlans:[],analysisSelection:[],analysisInitialized:true,forecast:[],openingBalances:{cash:0,invest:0,other:0}};return {ctx,nodes};
}
function cat(id,group,type,planned,extra={}){return {id,name:id,group,type,scope:'master',active:true,defaultPlanned:planned,...extra}}
function row(month,status,values,extra={}){return {month,status,values,balances:{cash:null,invest:null},...extra}}
const tests=[];function test(name,run){tests.push([name,run])}
test('実績合計は古い集計値より編集欄の明細を使う',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',250000)];const r=row('2026-10','closed',{pay:{planned:250000,actual:270000,actualEntered:true}},{aggregateActual:{salary:330000}});c.data.months=[r];assert.equal(c.monthFlow(r.month).income,c.totals(r).income);assert.equal(c.totals(r).income,270000)});
test('入力途中は入力済み実績と未入力の予定を合算する',()=>{const {ctx:c}=environment();c.data.categories=[cat('a','生活費','expense',10000),cat('b','生活費','expense',20000)];c.data.months=[row('2026-10','draft',{a:{planned:10000,actual:8000,actualEntered:true},b:{planned:20000,actual:0,actualEntered:false}})];assert.equal(c.monthFlow('2026-10').expense,28000)});
test('実績確定では未入力の投資も0円になり月の記録と一致する',()=>{const {ctx:c}=environment();c.data.categories=[cat('nisa','NISA','investment',50000)];const r=row('2026-10','closed',{nisa:{planned:50000,actual:0,actualEntered:false}});c.data.months=[r];assert.equal(c.monthFlow(r.month).investment,c.totals(r).investment)});
test('未来に追加した月に変更後の予定を引き継ぐ',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',250000)];c.data.planRules=[{categoryId:'pay',startMonth:'2026-10',amount:300000}];const r=c.ensureMonth('2027-01');assert.equal(c.displayedPlanned(c.data.categories[0],r),300000);assert.equal(c.planFor(r.month).salary,300000)});
test('この月だけの変更は他の月以降の変更で上書きしない',()=>{const {ctx:c}=environment(),x=cat('pay','給料','income',250000);c.data.categories=[x];c.data.months=[row('2026-12','planned',{pay:{planned:400000,plannedOverride:true,actual:0}})];c.applyCategoryPlan(x,'2026-10',300000,'future');assert.equal(c.plannedAt(x,'2026-12'),400000);assert.equal(c.plannedAt(x,'2026-11'),300000)});
test('NISA費目が複数でも予定が二重計上されない',()=>{const {ctx:c}=environment();c.data.categories=[cat('a','NISA','investment',50000),cat('b','NISA','investment',10000)];const r=row('2026-10','planned',{a:{planned:50000},b:{planned:10000}});c.data.months=[r];assert.equal(c.data.categories.reduce((s,x)=>s+c.displayedPlanned(x,r),0),c.planFor(r.month).nisa)});
test('意図的な標準予定0円は再読み込みで過去の金額に戻さない',()=>{const {ctx:c}=environment();c.data.categories=[cat('a','生活費','expense',0)];c.data.months=[row('2026-09','closed',{a:{planned:10000,actual:5000}})];assert.equal(c.migrate(c.data).categories[0].defaultPlanned,0)});
test('削除した費目は実績合計とホームの双方から除外する',()=>{const {ctx:c}=environment();c.data.categories=[cat('a','生活費','expense',0,{active:false})];const r=row('2026-10','closed',{a:{planned:10000,actual:10000}},{aggregateActual:{living:10000}});c.data.months=[r];assert.equal(c.totals(r).expense,0);assert.equal(c.monthFlow(r.month).expense,0)});
test('ホームと月の記録の予定差は特別な予定を含めて一致する',()=>{const {ctx:c,nodes}=environment();c.data.categories=[cat('pay','給料','income',250000),cat('living','生活費','expense',120000)];const r=row('2026-10','closed',{pay:{planned:250000,actual:250000},living:{planned:120000,actual:100000}});c.data.months=[r];c.data.planMonths=[{month:r.month,salary:330000,living:75582,specialExpense:150000}];c.renderMonthBudget(r);const flow=c.monthFlow(r.month);assert.equal(flow.plannedAssetChange,-20000);assert(nodes.monthBudgetBody.innerHTML.includes('収支の予定</span><strong>-20,000円'));assert(nodes.monthBudgetTitle.innerHTML.includes('+170,000円'));assert(c.outlookCard(flow).includes('+170,000円'))});
test('月が飛んだ予定でも間の月を含めて残高を計算する',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',100000)];c.data.planMonths=[{month:'2026-10'},{month:'2027-01'}];const rows=c.timeline();assert.equal(rows.length,4);assert.equal(rows.at(-1).total,400000)});
test('NISAと別枠貯金への移動で合計資産を増減させない',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',300000),cat('expense','生活費','expense',200000),cat('nisa','NISA','investment',50000),cat('reserve','別枠貯金','reserve',20000)];c.data.planMonths=[{month:'2026-10',purposeSaving:20000}];const r=c.timeline()[0];assert.equal(r.cash,30000);assert.equal(r.invest,50000);assert.equal(r.other,20000);assert.equal(r.total,100000);assert.equal(r.assetChange,100000)});
test('集計だけを持つ旧データも消さずに月別集計へ引き継ぐ',()=>{const {ctx:c}=environment();const r=row('2026-10','closed',{}, {aggregateActual:{salary:300000,living:200000,nisa:50000}});c.data.months=[r];assert.equal(c.totals(r).income,300000);assert.equal(c.totals(r).expense,200000);assert.equal(c.monthFlow(r.month).income,300000)});
test('複数の別枠貯金の月限定額を二重計上しない',()=>{const {ctx:c}=environment();const a=cat('a','別枠貯金','reserve',10000),b=cat('b','別枠貯金','reserve',10000);c.data.categories=[a,b];c.data.planMonths=[{month:'2026-10',purposeSaving:20000}];c.ensureMonth('2026-10');c.applyCategoryPlan(b,'2026-10',30000,'only');assert.equal(c.plannedAt(a,'2026-10'),10000);assert.equal(c.plannedAt(b,'2026-10'),30000);assert.equal(c.planFor('2026-10').purposeSaving,40000)});
test('別枠貯金の月限定額は前月からの将来変更で上書きしない',()=>{const {ctx:c}=environment();const a=cat('a','別枠貯金','reserve',20000);c.data.categories=[a];c.data.planMonths=[{month:'2026-10',purposeSaving:20000},{month:'2026-12',purposeSaving:40000}];c.data.months=[row('2026-12','planned',{a:{planned:40000,plannedOverride:true,actual:0}})];c.applyCategoryPlan(a,'2026-10',30000,'future');assert.equal(c.planFor('2026-12').purposeSaving,40000);assert.equal(c.plannedAt(a,'2026-12'),40000);assert.equal(c.planFor('2026-11').purposeSaving,30000)});
test('当月だけの給与費目の予定と実績も収入に含める',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',250000),cat('one','給料','income',0,{scope:'month',month:'2026-10'})];c.data.months=[row('2026-10','draft',{pay:{planned:250000,actual:0,actualEntered:false},one:{planned:10000,actual:8000,actualEntered:true}})];assert.equal(c.planFor('2026-10').salary,260000);assert.equal(c.monthFlow('2026-10').income,258000);assert.equal(c.planFor('2026-11').salary,250000)});
test('バックアップを読み直しても予定と実績の金額が変わらない',()=>{const {ctx:c}=environment();c.data.categories=[cat('pay','給料','income',0),cat('cost','生活費','expense',10000)];c.data.planRules=[{id:'r',categoryId:'pay',startMonth:'2026-10',amount:250000}];c.data.months=[row('2026-10','closed',{pay:{planned:200000,actual:260000},cost:{planned:10000,actual:8000}},{aggregateActual:{salary:330000,living:10000}})];const before=JSON.stringify(c.monthFlow('2026-10').used);c.data=c.migrate(JSON.parse(JSON.stringify(c.data)));assert.equal(JSON.stringify(c.monthFlow('2026-10').used),before);assert.equal(c.data.categories[0].defaultPlanned,0);assert.equal(c.planFor('2026-10').salary,250000)});
test('200通りの確定月でホーム・月の記録・資産残高の計算が一致する',()=>{for(let i=0;i<200;i++){const {ctx:c}=environment();const specs=[['給料','income'],['生活費','expense'],['固定費','expense'],['定期支出','expense'],['NISA','investment'],['別枠貯金','reserve']];c.data.categories=specs.map(([g,t],j)=>cat('c'+j,g,t,(i*7919+j*3571)%200000));const values=Object.fromEntries(c.data.categories.map((x,j)=>[x.id,{planned:x.defaultPlanned,actual:(i*1237+j*4567)%180000,actualEntered:j%2===0}]));const r=row('2026-10','closed',values,{aggregateActual:{salary:999999,living:888888,nisa:777777,purposeSaving:666666}});c.data.months=[r];c.data.planMonths=[{month:r.month,purposeSaving:c.data.categories[5].defaultPlanned}];const f=c.monthFlow(r.month),t=c.totals(r),end=c.timeline()[0];assert.equal(f.income,t.income);assert.equal(f.expense,t.expense);assert.equal(f.investment,t.investment);assert.equal(f.reserve,t.reserve);assert.equal(f.netCash,t.net);assert.equal(end.total,f.assetChange);assert.equal(end.total,end.cash+end.invest+end.other)}});
let failed=0;for(const [name,run]of tests){try{run();console.log('PASS '+name)}catch(e){failed++;console.log('FAIL '+name+'\n'+e.message)}}if(failed)process.exitCode=1;
