(()=>{
const KEY='household-book-v1',$=id=>document.getElementById(id),n=x=>Number(String(x??'').replaceAll(',',''))||0,fmt=x=>new Intl.NumberFormat('ja-JP').format(Math.round(n(x))),yen=x=>fmt(x)+'円',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=()=>crypto.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2),monthNow=()=>new Date().toISOString().slice(0,7),fiscal=m=>{const [y,mo]=m.split('-').map(Number);return mo>=4?y:y-1};
const defaults=[
 ['収入','給料','income'],['収入','特別収入','income'],
 ['固定費','電気','expense'],['固定費','ガス','expense'],['固定費','水道','expense'],['固定費','通信','expense'],['固定費','サブスク','expense'],
 ['食費','自炊','expense'],['食費','外食','expense'],['食費','食堂','expense'],['食費','飲み会','expense'],
 ['交通費','仕事','expense'],['交通費','私用','expense'],['交通費','その他','expense'],
 ['生活費','日用品','expense'],['生活費','医療','expense'],['生活費','被服','expense'],['生活費','旅行','expense'],['生活費','趣味','expense'],['生活費','ビジネス','expense'],['生活費','交際費','expense'],
 ['資産形成','NISA・投資','investment'],['定期支出','定期支出','expense'],['特別支出','特別支出','expense']
];
const fresh=()=>({format:'jp.household.book',schemaVersion:1,updatedAt:new Date().toISOString(),categories:defaults.map(([group,name,type])=>({id:uuid(),group,name,type,order:0,active:true})),months:[]});
let data=fresh(),activeMonth='';try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.format==='jp.household.book')data=saved}catch{}
function save(){data.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(data));$('saveState').textContent='自動保存済み'}catch{$('saveState').textContent='保存できませんでした'}}
function ensureMonth(month=monthNow(),copyFrom=''){let row=data.months.find(x=>x.month===month);if(row)return row;const source=data.months.find(x=>x.month===copyFrom);row={id:uuid(),month,fiscalYear:fiscal(month),values:{},balances:{cash:0,invest:0},comment:''};if(source)for(const [id,v] of Object.entries(source.values||{}))row.values[id]={planned:n(v.planned),actual:0,comment:''};data.months.push(row);data.months.sort((a,b)=>b.month.localeCompare(a.month));save();return row}
if(!data.months.length)ensureMonth(monthNow());activeMonth=data.months[0].month;
const catMap=()=>Object.fromEntries(data.categories.map(c=>[c.id,c]));
function value(row,id){return row.values[id]||{planned:0,actual:0,comment:''}}
function totals(row){const cats=catMap();let income=0,expense=0,investment=0,reserve=0,plannedIncome=0,plannedExpense=0;for(const [id,v] of Object.entries(row.values||{})){const type=cats[id]?.type;if(type==='income'){income+=n(v.actual);plannedIncome+=n(v.planned)}else if(type==='investment')investment+=n(v.actual);else if(type==='reserve')reserve+=n(v.actual);else{expense+=n(v.actual);plannedExpense+=n(v.planned)}}return {income,expense,investment,reserve,net:income-expense-investment-reserve,plannedIncome,plannedExpense}}
function selectedRows(period=0){const rows=[...data.months].sort((a,b)=>b.month.localeCompare(a.month));return period?rows.slice(0,period):rows}
function decorate(){document.querySelectorAll('[data-money]').forEach(el=>{el.inputMode='decimal';if(document.activeElement!==el&&el.value!=='')el.value=fmt(el.value);el.onfocus=()=>el.select()})}
function renderNav(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));render()})}
function renderHome(){const latest=selectedRows()[0],t=totals(latest),all=selectedRows(3),avg=all.length?all.reduce((s,r)=>s+totals(r).expense,0)/all.length:0;$('homeCards').innerHTML=`<article><span>${latest.month}の収入</span><strong>${yen(t.income)}</strong></article><article><span>${latest.month}の支出</span><strong>${yen(t.expense+t.investment+t.reserve)}</strong></article><article><span>今月の収支</span><strong class="${t.net<0?'negative':'positive'}">${yen(t.net)}</strong></article><article><span>直近3か月の生活支出平均</span><strong>${yen(avg)}</strong></article><article><span>最新の現金</span><strong>${yen(latest.balances?.cash)}</strong></article><article><span>最新の投資</span><strong>${yen(latest.balances?.invest)}</strong></article>`;renderCashflow();renderBreakdown(latest);$('homeNotice').textContent=data.months.length<3?'3か月以上記録すると、平均と傾向を確認しやすくなります。':'実績はライフプランの予定額を見直す材料として書き出せます。'}
function renderCashflow(){const rows=[...data.months].sort((a,b)=>a.month.localeCompare(b.month));if(!rows.length){$('cashflowChart').innerHTML='<p>記録がありません。</p>';return}const W=760,H=270,L=55,R=15,T=20,B=42,vals=rows.flatMap(r=>{const t=totals(r);return [t.income,t.expense+t.investment+t.reserve]}),max=Math.max(10000,...vals),x=i=>L+(i+.5)*(W-L-R)/rows.length,y=v=>T+(max-v)/(max||1)*(H-T-B),w=Math.max(8,Math.min(28,(W-L-R)/rows.length*.3));$('cashflowChart').innerHTML=`<div class="chart-legend"><span><i class="legend-dot" style="background:#167e78"></i>収入</span><span><i class="legend-dot" style="background:#d67a39"></i>支出・投資・積立</span></div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="月ごとの収入と支出"><line x1="${L}" x2="${W-R}" y1="${H-B}" y2="${H-B}" stroke="#79949e"/>${rows.map((r,i)=>{const t=totals(r),xx=x(i);return `<rect x="${xx-w-1}" y="${y(t.income)}" width="${w}" height="${H-B-y(t.income)}" fill="#167e78"><title>${r.month} 収入 ${yen(t.income)}</title></rect><rect x="${xx+1}" y="${y(t.expense+t.investment+t.reserve)}" width="${w}" height="${H-B-y(t.expense+t.investment+t.reserve)}" fill="#d67a39"><title>${r.month} 支出 ${yen(t.expense+t.investment+t.reserve)}</title></rect><text x="${xx}" y="${H-14}" text-anchor="middle" font-size="11">${r.month.slice(2)}</text>`}).join('')}</svg>`}
function renderBreakdown(row){const groups={};for(const c of data.categories.filter(x=>x.type==='expense'))groups[c.group]=(groups[c.group]||0)+n(value(row,c.id).actual);const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));$('expenseBreakdown').innerHTML=entries.length?entries.map(([name,v])=>`<p><strong>${esc(name)}</strong> ${yen(v)}</p><div style="height:8px;background:#e7f0f1;border-radius:8px"><span style="display:block;width:${v/max*100}%;height:100%;background:#328b92;border-radius:8px"></span></div>`).join(''):'<p>支出を入力すると内訳を表示します。</p>'}
function renderMonth(){const row=ensureMonth(activeMonth||monthNow());$('monthSelect').innerHTML=data.months.map(r=>`<option value="${r.month}" ${r.month===row.month?'selected':''}>${r.month}（${r.fiscalYear}年度）</option>`).join('');const t=totals(row);$('monthSummary').innerHTML=`<article><span>収入</span><strong>${yen(t.income)}</strong></article><article><span>支出</span><strong>${yen(t.expense+t.investment+t.reserve)}</strong></article><article><span>収支</span><strong class="${t.net<0?'negative':'positive'}">${yen(t.net)}</strong></article>`;const groups=[...new Set(data.categories.filter(c=>c.active).map(c=>c.group))];$('monthGroups').innerHTML=groups.map(group=>{const cats=data.categories.filter(c=>c.active&&c.group===group),sum=cats.reduce((s,c)=>s+n(value(row,c.id).actual),0);return `<details class="group"><summary>${esc(group)} <small>実績 ${yen(sum)}</small></summary>${cats.map(c=>{const v=value(row,c.id);return `<div class="entry entry-grid" data-category="${c.id}"><strong class="category-name">${esc(c.name)}</strong><label>予定<input data-money data-field="planned" value="${v.planned||''}" inputmode="decimal"></label><label>実績<input data-money data-field="actual" value="${v.actual||''}" inputmode="decimal"></label><label class="item-comment">コメント<input data-field="comment" value="${esc(v.comment||'')}" placeholder="任意"></label></div>`}).join('')}</details>`}).join('');$('cashBalance').value=row.balances?.cash||'';$('investBalance').value=row.balances?.invest||'';$('monthComment').value=row.comment||'';decorate()}
function analysisRows(period){const rows=selectedRows(period),result=[];for(const c of data.categories.filter(x=>x.active)){const vals=rows.map(r=>value(r,c.id)),used=vals.filter(v=>n(v.actual)||n(v.planned));if(!used.length)continue;result.push({cat:c,months:used.length,planned:used.reduce((s,v)=>s+n(v.planned),0)/used.length,actual:used.reduce((s,v)=>s+n(v.actual),0)/used.length})}return result}
function renderAnalysis(){const period=n($('averagePeriod').value||3),rows=analysisRows(period),months=selectedRows(period),avgIncome=months.length?months.reduce((s,r)=>s+totals(r).income,0)/months.length:0,avgOut=months.length?months.reduce((s,r)=>{const t=totals(r);return s+t.expense+t.investment+t.reserve},0)/months.length:0;$('analysisCards').innerHTML=`<article><span>平均収入</span><strong>${yen(avgIncome)}</strong></article><article><span>平均支出</span><strong>${yen(avgOut)}</strong></article><article><span>平均収支</span><strong class="${avgIncome-avgOut<0?'negative':'positive'}">${yen(avgIncome-avgOut)}</strong></article>`;$('averageTable').innerHTML=`<table><thead><tr><th>費目</th><th>予定平均</th><th>実績平均</th><th>差</th><th>記録月</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.cat.group)}／${esc(r.cat.name)}</th><td>${yen(r.planned)}</td><td>${yen(r.actual)}</td><td class="${r.cat.type==='income'?(r.actual<r.planned?'negative':'positive'):(r.actual>r.planned?'negative':'positive')}">${yen(r.actual-r.planned)}</td><td>${r.months}</td></tr>`).join('')}</tbody></table>`;const candidates=rows.filter(r=>r.planned>0&&r.months>=2).sort((a,b)=>Math.abs(b.actual-b.planned)-Math.abs(a.actual-a.planned)).slice(0,5);$('insights').innerHTML=candidates.length?candidates.map(r=>{const gap=r.actual-r.planned;if(Math.abs(gap)<100)return'';return `<p><strong>${esc(r.cat.name)}</strong>は予定より月平均${yen(Math.abs(gap))}${gap>0?'多い':'少ない'}実績です。ライフプランの予定額を${yen(Math.round(r.actual/100)*100)}前後で比較できます。</p>`}).join(''):'<p>予定と実績を2か月以上入力すると、差が大きい項目を表示します。</p>'}
function renderManager(){$('categoryManager').innerHTML=data.categories.map((c,i)=>`<div class="entry entry-grid" data-manage="${c.id}"><label class="category-name">大項目<input data-cat="group" value="${esc(c.group)}"></label><label>費目名<input data-cat="name" value="${esc(c.name)}"></label><label>種類<select data-cat="type"><option value="expense" ${c.type==='expense'?'selected':''}>支出</option><option value="income" ${c.type==='income'?'selected':''}>収入</option><option value="investment" ${c.type==='investment'?'selected':''}>投資</option><option value="reserve" ${c.type==='reserve'?'selected':''}>用途別積立</option></select></label><button data-remove-cat="${c.id}" class="danger">削除</button></div>`).join('')}
function render(){const page=document.querySelector('.page.active')?.id;if(page==='home')renderHome();if(page==='month')renderMonth();if(page==='analysis')renderAnalysis();if(page==='data')renderManager();decorate()}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function linkExport(){const period=n($('linkPeriod').value),rows=selectedRows(period),cats=catMap(),months=rows.map(r=>{const items=Object.entries(r.values||{}).map(([id,v])=>({categoryId:id,group:cats[id]?.group||'',name:cats[id]?.name||'',type:cats[id]?.type||'expense',planned:n(v.planned),actual:n(v.actual),comment:v.comment||''}));const t=totals(r);return {month:r.month,fiscalYear:fiscal(r.month),income:t.income,living:t.expense,investment:t.investment,purposeSaving:t.reserve,net:t.net,cashBalance:n(r.balances?.cash),investBalance:n(r.balances?.invest),comment:r.comment||'',items}});return {format:'jp.household.actuals',schemaVersion:1,exportedAt:new Date().toISOString(),periodMonths:period||months.length,months}}
function readJson(file,done,status){const reader=new FileReader();reader.onload=()=>{try{done(JSON.parse(reader.result));$(status).textContent='読み込みました。'}catch(err){$(status).textContent='読み込めませんでした：'+err.message}};reader.readAsText(file,'utf-8')}
document.addEventListener('input',e=>{const row=data.months.find(x=>x.month===activeMonth);if(e.target.dataset.field&&row){const id=e.target.closest('[data-category]')?.dataset.category;row.values[id]||={planned:0,actual:0,comment:''};row.values[id][e.target.dataset.field]=e.target.dataset.field==='comment'?e.target.value:n(e.target.value);save();renderMonth()}if(e.target.id==='cashBalance'){row.balances.cash=n(e.target.value);save()}if(e.target.id==='investBalance'){row.balances.invest=n(e.target.value);save()}if(e.target.id==='monthComment'){row.comment=e.target.value;save()}if(e.target.dataset.cat){const c=data.categories.find(x=>x.id===e.target.closest('[data-manage]').dataset.manage);c[e.target.dataset.cat]=e.target.value;save()}});
document.addEventListener('click',e=>{const id=e.target.dataset.removeCat;if(id){data.categories.find(c=>c.id===id).active=false;save();renderManager()}if(e.target.id==='confirmCategory'){e.preventDefault();const name=$('newCategoryName').value.trim(),group=$('newGroup').value.trim();if(!name||!group)return;data.categories.push({id:uuid(),group,name,type:$('newCategoryType').value,order:data.categories.length,active:true});save();$('categoryDialog').close();render()}});
$('monthSelect').onchange=e=>{activeMonth=e.target.value;renderMonth()};$('addMonth').onclick=()=>{const next=prompt('追加する月（YYYY-MM）',monthNow());if(next&&/^\d{4}-(0[1-9]|1[0-2])$/.test(next)){ensureMonth(next);activeMonth=next;renderMonth()}};$('newMonth').onclick=()=>{ensureMonth(monthNow());activeMonth=monthNow();document.querySelector('[data-page=month]').click()};$('copyMonth').onclick=()=>{const rows=[...data.months].sort((a,b)=>a.month.localeCompare(b.month)),i=rows.findIndex(x=>x.month===activeMonth),src=rows[i-1];if(!src)return alert('前月の記録がありません。');const row=ensureMonth(activeMonth);for(const [id,v] of Object.entries(src.values||{}))row.values[id]={...(row.values[id]||{}),planned:n(v.planned)};save();renderMonth()};$('duplicateMonth').onclick=()=>{const next=prompt('複製先の月（YYYY-MM）','');if(next){ensureMonth(next,activeMonth);activeMonth=next;renderMonth()}};$('deleteMonth').onclick=()=>{if(!confirm(activeMonth+'の記録を削除しますか？'))return;data.months=data.months.filter(x=>x.month!==activeMonth);if(!data.months.length)ensureMonth(monthNow());activeMonth=data.months[0].month;save();renderMonth()};
const openCategory=()=>{$('newGroup').value='';$('newCategoryName').value='';$('categoryDialog').showModal()};$('addCategory').onclick=openCategory;$('addManagedCategory').onclick=openCategory;$('averagePeriod').onchange=renderAnalysis;$('exportAll').onclick=()=>download('家計簿バックアップ-'+monthNow()+'.json',data);$('exportLink').onclick=()=>{download('ライフプラン連携-'+monthNow()+'.json',linkExport());$('linkStatus').textContent='連携ファイルを書き出しました。'};$('importAll').onchange=e=>e.target.files[0]&&readJson(e.target.files[0],obj=>{if(obj.format!=='jp.household.book')throw Error('家計簿バックアップではありません');data=obj;activeMonth=data.months[0]?.month||monthNow();save();render()},'dataStatus');$('importLink').onchange=e=>e.target.files[0]&&readJson(e.target.files[0],obj=>{if(obj.format!=='jp.household.actuals')throw Error('連携ファイルではありません');$('linkStatus').textContent=`${obj.months?.length||0}か月分を確認しました。`},'linkStatus');$('resetAll').onclick=()=>{if(!confirm('この端末の家計簿を初期化しますか？'))return;data=fresh();ensureMonth(monthNow());activeMonth=monthNow();save();render()};
renderNav();render();
})();

