(()=>{
const KEY='household-book-v1',$=id=>document.getElementById(id),n=x=>Number(String(x??'').replaceAll(',',''))||0,fmt=x=>new Intl.NumberFormat('ja-JP').format(Math.round(n(x))),yen=x=>fmt(x)+'円',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=()=>crypto.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2),monthNow=()=>new Date().toISOString().slice(0,7),fiscal=m=>{const [y,mo]=m.split('-').map(Number);return mo>=4?y:y-1};
const defaults=[
 ['給料','基本給','income'],['給料','立替交通費','income'],['給料','残業代','income'],['給料','その他','income'],
 ...['①','②','③','④'].map(x=>['特別収入',x,'income']),
 ...['電気','ガス','水道','通信','サブスク'].map(x=>['固定費',x,'expense']),
 ...['家','家り','外１','外り','外友','食堂','飲み'].map(x=>['食費',x,'expense']),
 ...['仕事','り','他'].map(x=>['交通費',x,'expense']),
 ...['日用品','医療','被服','旅行','趣味','ビジネス','交際費'].map(x=>['生活費',x,'expense']),
 ['NISA','NISA','investment'],['定期支出','①るり','expense'],['定期支出','②スマホ','expense'],['定期支出','③家族','expense'],
 ...['①','②','③','④'].map(x=>['特別支出',x,'expense'])
];
const fresh=()=>({format:'jp.household.book',schemaVersion:2,updatedAt:new Date().toISOString(),categories:defaults.map(([group,name,type],order)=>({id:'cat-'+order,group,name,type,order,active:true})),months:[],recurringPlans:[],analysisSelection:[],forecast:[],sourceInfo:null,sourceArchive:null});
function migrate(x){if(!x||x.format!=='jp.household.book')return fresh();x.schemaVersion=2;x.categories||=fresh().categories;x.months||=[];x.recurringPlans||=[];x.analysisSelection||=[];x.forecast||=[];x.months.forEach(m=>{m.values||={};m.balances||={cash:0,invest:0};m.fiscalYear??=fiscal(m.month)});return x}
let data=fresh(),activeMonth='';try{data=migrate(JSON.parse(localStorage.getItem(KEY)))}catch{}
function save(){data.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(data));$('saveState').textContent='自動保存済み'}catch{$('saveState').textContent='保存できませんでした'}}
function ensureMonth(month=monthNow(),copyFrom=''){let row=data.months.find(x=>x.month===month);if(row)return row;const source=data.months.find(x=>x.month===copyFrom);row={id:uuid(),month,fiscalYear:fiscal(month),values:{},balances:{cash:0,invest:0},comment:''};if(source)for(const [id,v] of Object.entries(source.values||{}))row.values[id]={planned:n(v.planned),actual:0,comment:''};for(const p of data.recurringPlans||[])if(p.startMonth<=month&&(!p.endMonth||p.endMonth>=month))row.values[p.categoryId]={planned:n(p.amount),actual:0,comment:''};data.months.push(row);data.months.sort((a,b)=>b.month.localeCompare(a.month));save();return row}
if(!data.months.length)ensureMonth(monthNow());activeMonth=data.months[0].month;
const catMap=()=>Object.fromEntries(data.categories.map(c=>[c.id,c]));
function value(row,id){return row.values[id]||{planned:0,actual:0,comment:''}}
function totals(row){const cats=catMap();let income=0,expense=0,investment=0,reserve=0,plannedIncome=0,plannedExpense=0;for(const [id,v] of Object.entries(row.values||{})){const type=cats[id]?.type;if(type==='income'){income+=n(v.actual);plannedIncome+=n(v.planned)}else if(type==='investment')investment+=n(v.actual);else if(type==='reserve')reserve+=n(v.actual);else{expense+=n(v.actual);plannedExpense+=n(v.planned)}}return {income,expense,investment,reserve,net:income-expense-investment-reserve,plannedIncome,plannedExpense}}
function selectedRows(period=0){const rows=[...data.months].sort((a,b)=>b.month.localeCompare(a.month));return period?rows.slice(0,period):rows}
function decorate(){document.querySelectorAll('[data-money]').forEach(el=>{el.inputMode='decimal';if(document.activeElement!==el&&el.value!=='')el.value=fmt(el.value);el.onfocus=()=>el.select()})}
function renderNav(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));render()})}
function renderHome(){const latest=selectedRows()[0],t=totals(latest),all=selectedRows(3),avg=all.length?all.reduce((s,r)=>s+totals(r).expense,0)/all.length:0;$('homeCards').innerHTML=`<article><span>${latest.month}の収入</span><strong>${yen(t.income)}</strong></article><article><span>${latest.month}の支出</span><strong>${yen(t.expense+t.investment+t.reserve)}</strong></article><article><span>今月の収支</span><strong class="${t.net<0?'negative':'positive'}">${yen(t.net)}</strong></article><article><span>直近3か月の生活支出平均</span><strong>${yen(avg)}</strong></article><article><span>最新の現金</span><strong>${yen(latest.balances?.cash)}</strong></article><article><span>最新の投資</span><strong>${yen(latest.balances?.invest)}</strong></article>`;renderCashflow();renderBreakdown(latest);$('homeNotice').textContent=data.months.length<3?'3か月以上記録すると、平均と傾向を確認しやすくなります。':'実績はライフプランの予定額を見直す材料として書き出せます。'}
function renderCashflow(){const rows=[...data.months].sort((a,b)=>a.month.localeCompare(b.month));if(!rows.length){$('cashflowChart').innerHTML='<p>記録がありません。</p>';return}const W=760,H=270,L=55,R=15,T=20,B=42,vals=rows.flatMap(r=>{const t=totals(r);return [t.income,t.expense+t.investment+t.reserve]}),max=Math.max(10000,...vals),x=i=>L+(i+.5)*(W-L-R)/rows.length,y=v=>T+(max-v)/(max||1)*(H-T-B),w=Math.max(8,Math.min(28,(W-L-R)/rows.length*.3));$('cashflowChart').innerHTML=`<div class="chart-legend"><span><i class="legend-dot" style="background:#167e78"></i>収入</span><span><i class="legend-dot" style="background:#d67a39"></i>支出・投資・積立</span></div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="月ごとの収入と支出"><line x1="${L}" x2="${W-R}" y1="${H-B}" y2="${H-B}" stroke="#79949e"/>${rows.map((r,i)=>{const t=totals(r),xx=x(i);return `<rect x="${xx-w-1}" y="${y(t.income)}" width="${w}" height="${H-B-y(t.income)}" fill="#167e78"><title>${r.month} 収入 ${yen(t.income)}</title></rect><rect x="${xx+1}" y="${y(t.expense+t.investment+t.reserve)}" width="${w}" height="${H-B-y(t.expense+t.investment+t.reserve)}" fill="#d67a39"><title>${r.month} 支出 ${yen(t.expense+t.investment+t.reserve)}</title></rect><text x="${xx}" y="${H-14}" text-anchor="middle" font-size="11">${r.month.slice(2)}</text>`}).join('')}</svg>`}
function renderBreakdown(row){const groups={};for(const c of data.categories.filter(x=>x.type==='expense'))groups[c.group]=(groups[c.group]||0)+n(value(row,c.id).actual);const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));$('expenseBreakdown').innerHTML=entries.length?entries.map(([name,v])=>`<p><strong>${esc(name)}</strong> ${yen(v)}</p><div style="height:8px;background:#e7f0f1;border-radius:8px"><span style="display:block;width:${v/max*100}%;height:100%;background:#328b92;border-radius:8px"></span></div>`).join(''):'<p>支出を入力すると内訳を表示します。</p>'}
function renderMonth(){const row=ensureMonth(activeMonth||monthNow());$('monthSelect').innerHTML=data.months.map(r=>`<option value="${r.month}" ${r.month===row.month?'selected':''}>${r.month}（${r.fiscalYear}年度）</option>`).join('');const t=totals(row);$('monthSummary').innerHTML=`<article><span>収入</span><strong>${yen(t.income)}</strong></article><article><span>支出・投資</span><strong>${yen(t.expense+t.investment+t.reserve)}</strong></article><article><span>収支</span><strong class="${t.net<0?'negative':'positive'}">${yen(t.net)}</strong></article>`;const groups=[...new Set(data.categories.filter(c=>c.active).map(c=>c.group))];$('monthGroups').innerHTML=groups.map(group=>{const cs=data.categories.filter(c=>c.active&&c.group===group),sum=cs.reduce((s,c)=>s+n(value(row,c.id).actual),0);return `<details class="group"><summary>${esc(group)} <small>実績 ${yen(sum)}</small></summary>${cs.map(c=>{const v=value(row,c.id);return `<div class="entry entry-grid" data-category="${c.id}"><strong class="category-name">${esc(c.name)}</strong><label>予定<input data-money data-field="planned" value="${v.planned||''}"></label><label>実績<input data-money data-field="actual" value="${v.actual||''}"></label><label class="item-comment">コメント<input data-field="comment" value="${esc(v.comment||'')}" placeholder="任意"></label><button type="button" data-repeat="${c.id}">今月以降もこの予定</button></div>`}).join('')}</details>`}).join('');$('cashBalance').value=row.balances?.cash||'';$('investBalance').value=row.balances?.invest||'';$('monthComment').value=row.comment||'';renderManager();renderRecurring();decorate()}
function analysisRows(period){const rows=selectedRows(period),result=[];for(const c of data.categories.filter(x=>x.active)){const vals=rows.map(r=>value(r,c.id)),used=vals.filter(v=>n(v.actual)||n(v.planned));if(!used.length)continue;result.push({cat:c,months:used.length,planned:used.reduce((s,v)=>s+n(v.planned),0)/used.length,actual:used.reduce((s,v)=>s+n(v.actual),0)/used.length})}return result}
function renderAnalysis(){const period=n($('averagePeriod').value||3),months=selectedRows(period),map=catMap(),chosen=(data.analysisSelection||[]).filter(id=>map[id]);$('analysisPicker').innerHTML=[...new Set(data.categories.filter(c=>c.active).map(c=>c.group))].map(g=>`<fieldset><legend><label><input type="checkbox" data-pick-group="${esc(g)}">${esc(g)}をまとめて選ぶ</label></legend>${data.categories.filter(c=>c.active&&c.group===g).map(c=>`<label><input type="checkbox" data-pick="${c.id}" ${chosen.includes(c.id)?'checked':''}>${esc(c.name)}</label>`).join('')}</fieldset>`).join('');const avg=id=>({p:months.reduce((s,m)=>s+n(value(m,id).planned),0)/Math.max(1,months.length),a:months.reduce((s,m)=>s+n(value(m,id).actual),0)/Math.max(1,months.length)});let p=0,a=0;chosen.forEach(id=>{const v=avg(id);p+=v.p;a+=v.a});$('analysisCards').innerHTML=`<article><span>選択した費目の予定平均</span><strong>${yen(p)}</strong></article><article><span>選択した費目の実績平均</span><strong>${yen(a)}</strong></article><article><span>予定との差</span><strong class="${a>p?'negative':'positive'}">${yen(a-p)}</strong></article>`;$('averageTable').innerHTML=`<table><thead><tr><th>費目</th><th>予定平均</th><th>実績平均</th><th>差</th></tr></thead><tbody>${chosen.map(id=>{const c=map[id],v=avg(id);return `<tr><th>${esc(c.group)}／${esc(c.name)}</th><td>${yen(v.p)}</td><td>${yen(v.a)}</td><td>${yen(v.a-v.p)}</td></tr>`}).join('')}</tbody></table>`;const gs={};chosen.forEach(id=>{const c=map[id],v=avg(id);gs[c.group]||={p:0,a:0};gs[c.group].p+=v.p;gs[c.group].a+=v.a});$('groupAverageTable').innerHTML=`<table><thead><tr><th>大項目</th><th>予定平均</th><th>実績平均</th></tr></thead><tbody>${Object.entries(gs).map(([g,v])=>`<tr><th>${esc(g)}</th><td>${yen(v.p)}</td><td>${yen(v.a)}</td></tr>`).join('')}</tbody></table>`;$('insights').innerHTML=chosen.length?`<p>${chosen.map(id=>esc(map[id].name)).join('＋')}の実績平均は<strong>${yen(a)}</strong>、予定との差は<strong>${yen(a-p)}</strong>です。</p>`:'<p>上で費目を選ぶと、食費＋交通費など好きな組み合わせの平均を表示します。</p>';if(data.forecast?.length){$('forecastBox').hidden=false;$('forecastTable').innerHTML=`<table><thead><tr><th>年月</th><th>給料</th><th>特別収入</th><th>生活費</th><th>固定費</th><th>NISA</th><th>定期支出</th><th>特別支出</th></tr></thead><tbody>${data.forecast.slice(0,120).map(x=>`<tr><td>${esc(x.month)}</td>${['salary','specialIncome','living','fixed','nisa','regular','specialExpense'].map(k=>`<td>${yen(x[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}else $('forecastBox').hidden=true}
function renderManager(){$('categoryManager').innerHTML=data.categories.filter(c=>c.active).map(c=>`<div class="manager-row" data-manage="${c.id}"><input data-cat="group" value="${esc(c.group)}" aria-label="大項目"><input data-cat="name" value="${esc(c.name)}" aria-label="費目名"><select data-cat="type"><option value="expense" ${c.type==='expense'?'selected':''}>支出</option><option value="income" ${c.type==='income'?'selected':''}>収入</option><option value="investment" ${c.type==='investment'?'selected':''}>投資</option><option value="reserve" ${c.type==='reserve'?'selected':''}>用途別積立</option></select><button data-copy-cat="${c.id}">複製</button><button data-remove-cat="${c.id}" class="danger">削除</button></div>`).join('')}
function renderRecurring(){$('recurringManager').innerHTML=(data.recurringPlans||[]).length?data.recurringPlans.map(p=>{const c=catMap()[p.categoryId];return `<div class="manager-row" data-plan="${p.id}"><strong>${esc(c?c.group+'／'+c.name:'削除済み費目')}</strong><label>月額<input data-plan-field="amount" data-money value="${p.amount||''}"></label><label>開始<input type="month" data-plan-field="startMonth" value="${p.startMonth}"></label><label>終了<input type="month" data-plan-field="endMonth" value="${p.endMonth||''}"></label><button data-remove-plan="${p.id}" class="danger">削除</button></div>`}).join(''):'<p class="hint">継続する予定はまだありません。各費目の「今月以降もこの予定」から登録できます。</p>'}
function renderSource(){const s=data.sourceInfo;$('sourceInfo').innerHTML=s?.sheets?.length?`<p><strong>${esc(s.fileName||'家計簿.xlsx')}</strong>から${s.sheets.length}シートを取り込みました。</p><ul>${s.sheets.map(x=>`<li>${esc(x.name)}：${n(x.nonEmptyCells)}セル</li>`).join('')}</ul><p class="hint">全シートの元データは、移行ファイル内の保管領域にも残しています。</p>`:'<p>Excelからの移行データはまだ読み込まれていません。</p>'}
function render(){const page=document.querySelector('.page.active')?.id;if(page==='home')renderHome();if(page==='month')renderMonth();if(page==='analysis')renderAnalysis();if(page==='data')renderSource();decorate()}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function linkExport(){const period=n($('linkPeriod').value),rows=selectedRows(period),cats=catMap(),months=rows.map(r=>{const items=Object.entries(r.values||{}).map(([id,v])=>({categoryId:id,group:cats[id]?.group||'',name:cats[id]?.name||'',type:cats[id]?.type||'expense',planned:n(v.planned),actual:n(v.actual),comment:v.comment||''}));const t=totals(r);return {month:r.month,fiscalYear:fiscal(r.month),income:t.income,living:t.expense,investment:t.investment,purposeSaving:t.reserve,net:t.net,cashBalance:n(r.balances?.cash),investBalance:n(r.balances?.invest),comment:r.comment||'',items}});return {format:'jp.household.actuals',schemaVersion:2,exportedAt:new Date().toISOString(),categories:data.categories.map(({id,group,name,type})=>({id,group,name,type})),periodMonths:period||months.length,months}}
function readJson(file,done,status){const reader=new FileReader();reader.onload=()=>{try{done(JSON.parse(reader.result));$(status).textContent='読み込みました。'}catch(err){$(status).textContent='読み込めませんでした：'+err.message}};reader.readAsText(file,'utf-8')}
document.addEventListener('change',e=>{const row=data.months.find(x=>x.month===activeMonth);if(e.target.dataset.field&&row){const id=e.target.closest('[data-category]')?.dataset.category;row.values[id]||={planned:0,actual:0,comment:''};row.values[id][e.target.dataset.field]=e.target.dataset.field==='comment'?e.target.value:n(e.target.value);save();renderMonth()}if(e.target.id==='cashBalance'){row.balances.cash=n(e.target.value);save()}if(e.target.id==='investBalance'){row.balances.invest=n(e.target.value);save()}if(e.target.id==='monthComment'){row.comment=e.target.value;save()}if(e.target.dataset.cat){const c=data.categories.find(x=>x.id===e.target.closest('[data-manage]').dataset.manage);c[e.target.dataset.cat]=e.target.value;save();renderMonth()}if(e.target.dataset.planField){const p=data.recurringPlans.find(x=>x.id===e.target.closest('[data-plan]').dataset.plan);p[e.target.dataset.planField]=e.target.dataset.planField==='amount'?n(e.target.value):e.target.value;save();renderMonth()}if(e.target.dataset.pick){const s=new Set(data.analysisSelection);e.target.checked?s.add(e.target.dataset.pick):s.delete(e.target.dataset.pick);data.analysisSelection=[...s];save();renderAnalysis()}if(e.target.dataset.pickGroup){const s=new Set(data.analysisSelection);data.categories.filter(c=>c.active&&c.group===e.target.dataset.pickGroup).forEach(c=>e.target.checked?s.add(c.id):s.delete(c.id));data.analysisSelection=[...s];save();renderAnalysis()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.removeCat;if(id){const c=data.categories.find(c=>c.id===id);if(confirm(`費目「${c.name}」を削除しますか？`)){c.active=false;data.analysisSelection=data.analysisSelection.filter(x=>x!==id);save();renderMonth()}}if(b.dataset.copyCat){const c=data.categories.find(x=>x.id===b.dataset.copyCat);data.categories.push({...c,id:uuid(),name:c.name+'（コピー）',order:data.categories.length});save();renderMonth()}if(b.dataset.repeat){const row=ensureMonth(activeMonth),v=value(row,b.dataset.repeat),old=data.recurringPlans.find(p=>p.categoryId===b.dataset.repeat&&!p.endMonth);if(old){old.startMonth=activeMonth;old.amount=n(v.planned)}else data.recurringPlans.push({id:uuid(),categoryId:b.dataset.repeat,startMonth:activeMonth,endMonth:'',amount:n(v.planned),note:''});save('毎月の予定として保存しました');renderMonth()}if(b.dataset.removePlan){data.recurringPlans=data.recurringPlans.filter(p=>p.id!==b.dataset.removePlan);save();renderMonth()}if(b.id==='confirmCategory'){e.preventDefault();const name=$('newCategoryName').value.trim(),group=$('newGroup').value.trim();if(!name||!group)return;data.categories.push({id:uuid(),group,name,type:$('newCategoryType').value,order:data.categories.length,active:true});save();$('categoryDialog').close();renderMonth()}});
$('monthSelect').onchange=e=>{activeMonth=e.target.value;renderMonth()};$('addMonth').onclick=()=>{const next=prompt('追加する月（YYYY-MM）',monthNow());if(next&&/^\d{4}-(0[1-9]|1[0-2])$/.test(next)){ensureMonth(next);activeMonth=next;renderMonth()}};$('newMonth').onclick=()=>{ensureMonth(monthNow());activeMonth=monthNow();document.querySelector('[data-page=month]').click()};$('copyMonth').onclick=()=>{const rows=[...data.months].sort((a,b)=>a.month.localeCompare(b.month)),i=rows.findIndex(x=>x.month===activeMonth),src=rows[i-1];if(!src)return alert('前月の記録がありません。');const row=ensureMonth(activeMonth);for(const [id,v] of Object.entries(src.values||{}))row.values[id]={...(row.values[id]||{}),planned:n(v.planned)};save();renderMonth()};$('duplicateMonth').onclick=()=>{const next=prompt('複製先の月（YYYY-MM）','');if(next){ensureMonth(next,activeMonth);activeMonth=next;renderMonth()}};$('deleteMonth').onclick=()=>{if(!confirm(activeMonth+'の記録を削除しますか？'))return;data.months=data.months.filter(x=>x.month!==activeMonth);if(!data.months.length)ensureMonth(monthNow());activeMonth=data.months[0].month;save();renderMonth()};
const openCategory=()=>{$('newGroup').value='';$('newCategoryName').value='';$('categoryDialog').showModal()};$('addCategory').onclick=openCategory;$('averagePeriod').onchange=renderAnalysis;$('selectAllAnalysis').onclick=()=>{data.analysisSelection=data.categories.filter(c=>c.active).map(c=>c.id);save();renderAnalysis()};$('clearAnalysis').onclick=()=>{data.analysisSelection=[];save();renderAnalysis()};$('exportAll').onclick=()=>download('家計簿バックアップ-'+monthNow()+'.json',data);$('exportLink').onclick=()=>{download('ライフプラン連携-'+monthNow()+'.json',linkExport());$('linkStatus').textContent='連携ファイルを書き出しました。'};$('importAll').onchange=e=>e.target.files[0]&&readJson(e.target.files[0],obj=>{if(obj.format!=='jp.household.book')throw Error('家計簿バックアップではありません');data=migrate(obj);activeMonth=data.months[0]?.month||monthNow();save();render()},'dataStatus');$('importLink').onchange=e=>e.target.files[0]&&readJson(e.target.files[0],obj=>{if(obj.format!=='jp.household.actuals')throw Error('連携ファイルではありません');$('linkStatus').textContent=`${obj.months?.length||0}か月分を確認しました。`},'linkStatus');$('resetAll').onclick=()=>{if(!confirm('この端末の家計簿を初期化しますか？'))return;data=fresh();ensureMonth(monthNow());activeMonth=monthNow();save();render()};
renderNav();render();
})();

